### PR TITLE
Add support for Rails 7.2

### PR DESCRIPTION
**Pull request by yenshirak**

### CODE REVIEW

**Comment by yenshirak** [comment]
@thhermansen It seems that there are issues with using EOL Ruby versions in CI. Is there a plan to stop supporting these? Can I help with anything?

**Comment by thhermansen** [comment]
Hi,

I have not worked with Ruby for a few years now. I'll ask someone in Skalar who still uses Ruby if they can maintain this lib.

**Comment by theodorton** [comment]
@yenshirak thank you for the contribution! Could you rebase on the latest `main` and change the restriction to `< 8`?

**Comment by yenshirak** [comment]
@theodorton done

**Comment by theodorton** [comment]
I’ll cut a new release tomorrow for this

**Pull request merged**
